import OccupancyGrid from "../components/OccupancyGrid";
import { useEchoMap } from "../context/EchoMapContext";

export default function Mapping() {
  const { liveData, connected } = useEchoMap();

  const mapping = liveData?.mapping ?? {
    currentLocation: { x: 10, y: 10 },
    destination: { name: "Computer Lab", x: 18, y: 15 },
    mapped_percentage: 0,
    exploredCells: 0,
    visited: [],
    obstacles: [],
    path: [],
  };

  return (
    <div className="page-container space-y-8">
      {/* Hero */}
      <section className="hero-banner">
        <p className="text-cyan-400 uppercase tracking-[0.25em] text-xs">
          MAPPING MODE
        </p>

        <h1 className="gradient-title text-5xl font-bold mt-3">
          Live Occupancy Grid
        </h1>

        <p className="text-slate-300 mt-4 max-w-4xl">
          Real-time SLAM map generated by EchoMap using Raspberry Pi ultrasonic
          sensors.
        </p>

        <div className="flex items-center gap-3 mt-6">
          <div
            className={`w-3 h-3 rounded-full ${
              connected ? "bg-green-400" : "bg-red-500"
            }`}
          />
          <span className="text-slate-300">
            {connected ? "Live Mapping Active" : "Offline Preview"}
          </span>
        </div>
      </section>

      {/* Stats */}
      <section className="grid md:grid-cols-4 gap-5">
        <div className="glass p-5 rounded-2xl">
          <p className="text-xs text-slate-400 uppercase">Mapped Area</p>
          <h2 className="text-3xl font-bold text-cyan-300 mt-2">
            {mapping.mapped_percentage}%
          </h2>
        </div>

        <div className="glass p-5 rounded-2xl">
          <p className="text-xs text-slate-400 uppercase">Explored Cells</p>
          <h2 className="text-3xl font-bold text-cyan-300 mt-2">
            {mapping.exploredCells}
          </h2>
        </div>

        <div className="glass p-5 rounded-2xl">
          <p className="text-xs text-slate-400 uppercase">Current Position</p>
          <h2 className="text-3xl font-bold text-cyan-300 mt-2">
            ({mapping.currentLocation.x}, {mapping.currentLocation.y})
          </h2>
        </div>

        <div className="glass p-5 rounded-2xl">
          <p className="text-xs text-slate-400 uppercase">Destination</p>
          <h2 className="text-xl font-bold text-white mt-2">
            {mapping.destination.name}
          </h2>
        </div>
      </section>

      {/* Existing Grid Component */}
      <section className="glass p-6 rounded-3xl">
        <OccupancyGrid />
      </section>
    </div>
  );
}