import VoiceConsolePanel from "../components/VoiceConsolePanel";
import VoiceTimeline from "../components/VoiceTimeline";
import { useEchoMap } from "../context/EchoMapContext";

export default function VoiceConsole() {
  const { connected, liveData } = useEchoMap();

  const navigation = liveData?.navigation ?? {
    instruction: "Waiting for destination...",
    voiceHistory: [],
  };

  return (
    <div className="page-container space-y-8">

      <section className="hero-banner">
        <p className="text-cyan-400 uppercase tracking-[0.2em] text-sm">
          VOICE CONSOLE
        </p>

        <h1 className="text-5xl font-bold gradient-title mt-3">
          EchoMap Speech Console
        </h1>

        <p className="text-slate-300 mt-4 max-w-3xl">
          Live speech announcements generated by Raspberry Pi navigation.
        </p>

        <div className="mt-4 flex items-center gap-3">
          <div
            className={`w-3 h-3 rounded-full ${
              connected ? "bg-green-400 animate-pulse" : "bg-red-500"
            }`}
          />

          <span className="text-slate-300">
            {connected ? "Speaker Active" : "Offline Preview"}
          </span>
        </div>
      </section>

      <VoiceConsolePanel
        instruction={navigation.instruction}
        connected={connected}
      />

      <VoiceTimeline history={navigation.voiceHistory} />

    </div>
  );
}